on:
    push:
      branches:
        - main
  
name: 🚀 Deploy website on push
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2
  
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@4.3.2
          with:
            server: dpkailashcollab.com
            username: test@102tcms.dpkailashcollab.com
            password: 7%#SH.oz8&*H